name: NASA Subdomain Scan
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install httpx
        run: |
          sudo apt update
          sudo apt install golang-go -y
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Run httpx
        run: httpx -l interesting_subs.txt -o results.txt -status-code -title -tech-detect -follow-redirects -threads 100 -timeout 5
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: httpx-results
          path: results.txt