name: NASA Secret Scan
on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install TruffleHog
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan NASA Org
        run: |
          trufflehog github --org=nasa --only-verified --json --concurrency=10 > nasa_verified.json

      - name: Upload Hasil
        uses: actions/upload-artifact@v4
        with:
          name: nasa-scan-results
          path: nasa_verified.json