name: NASA Secret Scan
on:
  workflow_dispatch:  # Bisa di-run manual

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          arguments: --org=nasa --only-verified --json
        continue-on-error: true

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: nasa-scan-results
          path: results.txt